### ISSUE TITLE
Web Interface can be made possible 

### ISSUE THREAD

**Issue by tmsagarofficial** [Know-Nepal/government-websites#29]
I would like to point out that there is no website or any interface to see all the details of different Nepal sites which are in the JSON file. So creating a webpage that can display the details from this JSON might help viewers know about each of these different sites and other info regarding the same.

Pls assign this issue to me so that i can work on this @TheLearneer @Saphall

**Comment by thenishantsapkota** [comment]
I've assigned the issue to you
Proceed with it

**Comment by tmsagarofficial** [comment]
> I've assigned the issue to you Proceed with it

Thanks for assigning. Will start working on it. 🚀

**Comment by thenishantsapkota** [comment]
@tmsagarofficial What's the update on the progress so far?
Would love to hear it :rocket:

**Comment by tmsagarofficial** [comment]
I think this will be a bit more tedious than expected as we have to think and start on a design so that all this data can be displayed in some specific UI

**Comment by thenishantsapkota** [comment]
The website has been created and can be accessed using https://government-websites.netlify.app.
#91 closes this
