### ISSUE TITLE
Website - Search not working properly

### ISSUE THREAD

**Issue by Rizina** [Know-Nepal/government-websites#95]
## Describe the bug

In the website when I goto a page > 1, for e.g. 10 and search for a specific website, the result doesn't show up.

## Expected behavior

When searching the page number should be changed to 1st and result should display properly

## Additional context

- [x] I would like to work on this issue

**Comment by TheLearneer** [comment]
Sure @Rizina assigned the issue to you

**Comment by TheLearneer** [comment]
Sorry @Rizina but seems like it was already reported and fixed 🙏
