### ISSUE TITLE
feat : update the favicon of this website 

### ISSUE THREAD

**Issue by tmsagarofficial** [Know-Nepal/government-websites#96]
I would like to point it out that we can add a custom favicon to go on with this site. 

Pls assign this to me so that i can work on a fix for this issue.

**Comment by thenishantsapkota** [comment]
Assigned it to you! Please work on it @tmsagarofficial

**Comment by thenishantsapkota** [comment]
We can use the Know Nepal logo for the favicon @tmsagarofficial

**Comment by thenishantsapkota** [comment]
I meant this logo https://avatars.githubusercontent.com/u/116947957?s=200&v=4
The logo you suggested is the logo of Government of Nepal
